# osl-dynamics version: 1.2.dev10
batch_size: 32
covariances_epsilon: 1.0e-06
covariances_regularizer: null
diagonal_covariances: false
gradient_clip: null
initial_covariances: null
initial_means: null
initial_trans_prob: null
learn_covariances: true
learn_means: false
learn_trans_prob: true
learning_rate: 0.0001
lr_decay: 0.1
means_regularizer: null
model_name: HMM
multi_gpu: false
multiple_dynamics: false
n_channels: 100
n_epochs: 20
n_modes: null
n_states: 10
observation_update_decay: 0.1
optimizer: adam
sequence_length: 2000
state_probs_t0: null
strategy: null
trans_prob_update_delay: 5
trans_prob_update_forget: 0.7
